name = "clangd"
description = "C/C++/Objective-C language server"
homepage = "https://clangd.llvm.org/"
licenses = ["Apache-2.0"]
languages = ["c", "cpp", "objc"]
file_extensions = ["c", "h", "cpp", "hpp", "cc", "cxx", "hxx", "m", "mm"]

[source]
type = "External"
command = "clangd"

[bin]
primary = "clangd"
additional = []
lsp_args = []
