name = "dockerfile-language-server"
description = "Dockerfile language server"
homepage = "https://github.com/rcjsuen/dockerfile-language-server-nodejs"
licenses = ["MIT"]
languages = ["dockerfile"]
file_extensions = ["Dockerfile", "dockerfile"]

[source]
type = "Npm"
package = "dockerfile-language-server-nodejs"

[bin]
primary = "docker-langserver"
additional = []
lsp_args = ["--stdio"]
