name = "svelte-language-server"
description = "Svelte language server"
homepage = "https://github.com/sveltejs/language-tools"
licenses = ["MIT"]
languages = ["svelte"]
file_extensions = ["svelte"]

[source]
type = "Npm"
package = "svelte-language-server"

[bin]
primary = "svelteserver"
additional = []
lsp_args = ["--stdio"]
